export const NUMERICAL_STATIONS = {
  POD: "Podgorica",
  TUZ: "Tuzi",
  ULC: "Ulcinj",
  BAR: "Bar",
  BUD: "Budva",
  KOT: "Kotor",
  TIV: "Tivat",
  HER: "Herceg Novi",
  CET: "Cetinje",
  DAN: "Danilovgrad",
  NIK: "Nikšić",
  SAV: "Šavnik",
  KOL: "Kolašin",
  PLU: "Plužine",
  PLA: "Plav",
  AND: "Andrijevica",
  GUS: "Gusinje",
  MOJ: "Mojkovac",
  BER: "Berane",
  ROZ: "Rožaje",
  BIJ: "Bijelo Polje",
  ZAB: "Žabljak",
  PLJ: "Pljevlja",
  ADB: "Ada Bojana",
  PET: "Petnjica",
} as const;
export type StationCode = keyof typeof NUMERICAL_STATIONS;
